#!/bin/bash

clear

service_name=waterworks-redis-cache.service
service_dir=/etc/systemd/system
server_dir=/srv/nodejs/senti/services/waterworks-redis-cache/production

service=$service_dir/$service_name

echo Registering Waterworks-redis-cache service for production ...


if [ ! -e "$service" ]; then
	echo
    echo "Waterworks-redis-cache service is not installed"
	echo "Installing Waterworks-redis-cache service ..."
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl start $service_name
else
    echo "Waterworks-redis-cache service is already installed, reinstalling"
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl stop $service_name
	sudo systemctl start $service_name
fi
